README.md

Previously had to run `gulp build` from `semantic` dir, now `yarn run build` from project dir executes `gulp build` for us. The readme incorrectly merged the two instructions.
Docs incorrectly had merged the old way of `gulp build` from the `semantic` dir, with the new way of `yarn run build` from the project dir.
Drop `semantic` dir from storybook startup instructions.
@cdaringe 
Closes #13

fix(pkg): storybook instructions in docs

---

semantic/src/themes/tripwire/elements/icon.variables

- fonts were not resolving
- drop duplicate font ref.  `elegant` is already in `site.overrides`

fix(fonts): drop dupelicate font ref

---

.gitignore
semantic/src/themes/tripwire/modules/modal.variables
src/components/suir/modal/Modal.examples.md
src/components/suir/modal/Modal.js

Added modal component
Added modal component

feat(Modal): Export modal component

---

src/components/LargeCard/LargeCard.examples.md
src/components/LargeCard/LargeCard.jsx
src/styles/components/large-card.css

enable relative positioning for large card
The large card component was originally designed to be displayed in absolute position.  This doesn't work if the intended usage changes to want to display multiple Large Card components.
Enable relative positioning.  This can be overridden by setting a style of position absolute whenever necessary.  Additionally the card was designed with a inset frame style display, this adds a flag which can enable/disable that framed display.  
Framed
Not Framed

Enable relative positioning for Large Card

---

src/components/charts/BarChart/BarChart.examples.md
src/components/charts/BarChart/BarChart.jsx
src/components/charts/BarChart/Rect.jsx

Adds prop to customize x axis font size.
See styleguidist for usage example.  Adds prop which accepts a string pixel size for font used as the X axis label.  Prop name is XLabelFontSize.

Support for custom x axis label size

---

src/components/LargeCard/LargeCardTitle.jsx

We needed LargeCard.Title divs for card title and description fields to have hover text, so that we can truncate long strings in display, but end user can still see full value on hover.
Add 'title' attribute to card title and description divs

feat(LargeCard): add title property

---

src/components/LargeCard/LargeCard.examples.md
src/components/LargeCard/LargeCardKeyValue.jsx
src/util/externalAttributeFilter.js

Users desire to use attributes such as `data-hook` on our components.
Starting with a somewhat small list of desired attributes, filter the props and apply them to the top-level element in the component. This change starts with LargeCardKeyValue, and will need to be applied to the other components.
BREAKING CHANGE: In LargeCardKeyValue, the `name` attribute has been changed to `label`, so that the top-level element in the component can support an arbitrary `name` attribute, and not conflict.
If this seems reasonable, I will then apply the same change to the rest of the components.

feat(util): allow custom attributes on components

---

src/components/LargeCard/LargeCard.examples.md
src/components/LargeCard/LargeCard.jsx
src/components/LargeCard/LargeCardAction.jsx
src/components/LargeCard/LargeCardClose.jsx
src/components/LargeCard/LargeCardContent.jsx
src/components/LargeCard/LargeCardGutter.jsx
src/components/LargeCard/LargeCardKeyValue.jsx
src/components/LargeCard/LargeCardRecentList.jsx
src/components/LargeCard/LargeCardStat.jsx
src/components/LargeCard/LargeCardTitle.jsx

Since the external attributes are working on `LargeCardKeyValue`, apply it to the rest of the `LargeCard` classes.
Apply the pattern!
BREAKING CHANGE: `LargeCard.Stat` had the `name` prop changed to `label`.
No visual changes. I smoke tested each component on the fly by adding `data-hook` through styleguidist.
This is another step towards addressing #57.

fix(LargeCard): use external attributes

---

src/components/charts/AreaChart/AreaChart.jsx
src/components/charts/BarChart/BarChart.jsx
src/components/charts/CircleChart/Circle.jsx
yarn.lock

We can't currently expand our UI automation until external attributes are
permitted in some of our react components.
Apply pattern used on `LargeCardKeyValue` to AreaChart, BarChart, and Circle
to allow data-hooks to be added to facilitate the addition of automated tests.
No visual changes. I smoke tested each component on the fly by adding data-hook through styleguidist.

fix(AreaChart, BarChart, Circle): use external attributes

---

src/components/MicroCard/MicroCard.jsx
src/components/MicroCard/MicroCardAction.jsx
src/components/MicroCard/MicroCardContent.jsx
src/components/MicroCard/MicroCardContentMessage.jsx
src/components/MicroCard/MicroCardContentStatus.jsx
src/components/MicroCard/MicroCardCount.jsx
src/components/MicroCard/MicroCardFavorite.jsx
src/components/MicroCard/MicroCardGutter.jsx

Automated testing of the UI requires allowing data-hooks which requires allowing external attributes.
Apply pattern used on `LargeCardKeyValue` to the MicroCard's in
src/components/MicroCard to allow data-hooks to be added to
facilitate the addition of automated tests.
No visual changes. I smoke tested each component on the fly by adding data-hook through styleguidist.

fix(MicrCard): use external attributes

---

src/components/LargeCard/LargeCard.jsx
src/util/externalAttributeFilter.js

The externalAttributeFilter regexes were too broad, and `on*` matched `description` for example.
Add needed line anchors to only match the intended prop names.
We should really bite the bullet and just start using Jest tests or anything really. Or I should have paid attention to the warnings in the browser console.

fix(props): unknown prop warnings

---

src/components/ThinCard/ThinCard.jsx
src/components/ThinCard/ThinCardActionButton.jsx
src/components/ThinCard/ThinCardDrawer.jsx
src/components/ThinCard/ThinCardPrimaryAction.jsx
src/components/ThinCard/ThinCardTitle.jsx
src/components/ThinCard/ThinCardWidget.jsx
src/components/ThinCard/ThinCardWidgetLabel.jsx
src/components/ThinCard/ThinCardWidgetValue.jsx

ThinCard needs external attributes like `data-hook=*`.
Apply the external attributes to all ThinCard components.
Continued changes to address #57.

fix(ThinCard): use external attributes

---

semantic/src/themes/tripwire/globals/site.variables

we bundle Lato locally, but pat noticed that the theme is also configured to pull in google fonts.
drop google fonts

fix(theme): drop dupe Lato font assets

---

src/components/ThinCard/ThinCardDrawer.jsx

The ThinCard component centers the expand button under the card, but our desired UX has it on the left.
Move the expand button to the left.
Here is the before and after:
**Before**
**After**

fix(ThinCardDrawer) Move expand button to the left

---

src/components/ThinCard/ThinCardPrimaryAction.jsx
src/components/ThinCard/ThinCardTitle.jsx
src/components/ThinCard/ThinCardWidget.jsx
src/components/ThinCard/ThinCardWidgetLabel.jsx
src/components/ThinCard/ThinCardWidgetValue.jsx

ThinCard components print warnings in dev mode when you pass them a `className` prop.
```
Warning: Failed prop type: Invalid prop `className` of type `string` supplied to `ThinCardWidgetLabel`, expected `object`.
in ThinCardWidgetLabel (created by PreviewComponent)
in PreviewComponent
in Wrapper
```
Change the className prop type on those components to 'string' instead of 'object'.
Other SUIR components define the className prop as being a string, so we should be consistent.
To test this, I added a className prop to each of these components and confirmed that I saw warnings about incorrect prop types, then confirmed that after I changed the PropTypes, they didn't print warnings anymore.

fix(props) className prop types

---

src/components/ThinCard/ThinCardDrawer.jsx
src/styles/components/thin-card.css

Expand button doesn't match mockups.
Shrink it down to 100px. Extract specific CSS classes for expand/collapse so we can easily tweak it in the future.
**Before**
**After**

fix(ThinCard) Make expand button smaller

---

src/components/ThinCard/ThinCardDrawer.jsx
src/styles/components/thin-card.css

The expand button on ThinCard is left aligned, but not the collapse button.
Make the collapse button left-aligned.
Since we're left-aligning the expand button, we left-align the collapse button text as well. It still expands to fill the full width below the card, however.

fix(ThinCard): Left align collapse button

---

src/components/suir/radio/Radio.js

- attempting to use `Radio` fails!
- fix import path
```
$ tree node_modules/semantic-ui-react/dist/commonjs/addons/Radio/
node_modules/semantic-ui-react/dist/commonjs/addons/Radio/
├── Radio.d.ts
├── Radio.js
├── index.d.ts
└── index.js
0 directories, 4 files
```

fix(Radio): patch broken export

---

semantic/src/themes/tripwire/elements/button.variables
src/components/suir/button/Button.examples.md

BREAKING CHANGE: buttons are now spaced wider apart from one another
(.25em to .5em)
- @yung wants wider spacing between buttons
- space'em out

feat(Buttons): space adjacent button

---

src/components/charts/CircleChart/Circle.examples.md
src/components/charts/CircleChart/Circle.jsx

When a CircleChart is sized to anything other than 110x110 it's center is offset.
don't use a hardcoded center for the circle.

fix(chart): Fix CircleChart resize issues

---

semantic/src/themes/tripwire/elements/button.overrides
semantic/src/themes/tripwire/elements/button.variables
semantic/src/themes/tripwire/elements/input.variables
src/components/suir/button/Button.examples.md

== DETAILS
Our style guide has focused down on three button styles only (generic, positive and negative), and this change set just updates that subset.  In all cases, the hover and active styles are darker than the default state, the active and focus states all have outlines.
See the image for details.
Note that the focus outlines don't really play well with ButtonGroups, but we aren't using these at this point so I think that that can be deferred until a later date.  For now, there are no outlines within button groups.  Given how SUIR doesn't use outlines at all, there's not a lot of support for outlines that overlap adjacent elements.  I think that this is fixable using z-index changes in the focus style but didn't feel that it was worth the time to dig in on this for a feature that …

feat(buttons): change styles to match UX preferences

---

src/styles/variables.css

== DETAILS
This changes #586A7B -> #586A7A.  Completely unnoticeable except when you are going over the UI verifying that the colors are what you expect.
== TESTS
Manually verified that it did the right thing.

fix(color): Slight tweak to color palette

---

package.json
src/components/charts/AreaChart/AreaChart.jsx
src/components/charts/AreaChart/ToolTip.jsx
src/components/charts/BarChart/BarChartTooltip.jsx

== DETAILS
We were depending on react directly and exposing this as a dependency for client apps.  This changeset moves react over to be a peer dependency.
Also fixed a number of noisy svg warnings where we weren't correctly using jxs compatible svg attribute names even though we were embedding them in jsx code.
== TESTS
Manual in the sylist page.

fix(deps): Move react into a peer dependency

---

package-lock.json
package.json
src/semantic-ui-theme/themes/tripwire/globals/site.overrides

We are using an older version of Lato Fonts
Upgrade Lato Fonts for more efficiency
V3 only supports .woff and .woff 2 which are supported by all modern browsers and are more efficient than .eot and .ttf
1) updated package.json
2) removed all references to .ttf and .eot in .overrides files

Upgraded Lato Fonts to version 3.

---

src/components/ThinCard/ThinCard.examples.md
src/styles/components/thin-card.css
src/styles/variables.css

Thin card button hover has wrong colors for hover.
The thin card expand and collapse buttons should have hover colors that match those used in the primary button.
This will entail changing how the draw color to the right of the collapse button is handled since it is separate and captures it's own hover events and we don't want there to be a split between the two segments in that panel.
Get correct color from UX Pin. Update variable w/ hexcode and use variable (no hexcodes in the css styles).
closes #122

Fixed Hover Colors on Thin Card

---

src/semantic-ui-theme/themes/tripwire/elements/button.overrides

Icon box-shadows overlap if they're both active. Meh. But we can fix it easily.
Let's standardize the margins based on the existing right margin (.8em) by adding top .4em and bottom .4em.
closes #117

fix(button): Fix the borders on the icon button. Currently they appear to overlap

---

package-lock.json
package.json

- old version of `snapjerk` doesn't generate reports correctly.
- new version of snapjerk generates reports with asset paths correct
- this was intended to go in with #138, but was stale on my machine
- given this is a strict dep update on a minor flag, i will eager merge on test pass, against normal biz process
- we should consider updating CONTRIBUTING.md to allow for minor/patch dep updates and **strict** doc updates to be eager merged by project owners

fix(tests): bump snapjerk s.t. html reports dont use bogus pathing

---

src/styles/components/pagination-control.css

1) Outline had a gap between bottom border and outline.
2) Left outline side was hidden by next button.
1) Needed to set overflow:hidden because font-size is 28px and max-height is 30px. It appears that outline is based on content of a container and not only container height.
2) I set position to relative and then set the z-index of button:focus to 1 (all others are auto).
Fixes #161

fix(pagination): Style updates to paginaton for Outline

---

CONTRIBUTING.md

per confluence task as a result of Pagination Retro:
"will create a "done is done" list in the CONTRIBUTING.md that specifies all of the required attributes of an Octagon UI component (data hooks, cross-browser testing, webjerk screen shots, usage example, etc.) by calendar icon16 Mar 2018"
We need Basic Acceptance Criteria in Contributing.md
Also, some mistakes in the current Contrib (bad markdown, spelling, grammar)
Add it!
- updated contrib w/ basic acceptance criteria
- moved testing to it's own section
- clean up - misspellings, grammar, markdown fixes, etc.

docs(contributing.md): Added Basic Acceptance Criteria (and some cleanup)

---

src/components/native/LeftNav/LeftNav.jsx
src/styles/components/left-nav.css

- `LeftNav` styles assumed too much about their usage context `height`
- make the styles of this component extensible. remove overly contextual assumptions
- we just did a `LeftNav` PR.  sorry i missed this in that one!  i've been doing a bottom up design, which meant i hadn't actually plugged this component into the app properly until moments ago

fix(LeftNav): remove evil styles, allow class extension

---

src/components/unstable/Layout/Layout.examples.md
src/components/unstable/LoginPane/LoginPane.css
src/components/unstable/LoginPane/LoginPane.examples.md
src/components/unstable/LoginPane/LoginPane.jsx
src/components/unstable/LoginPane/LoginPaneExamples.js

- some apps use libs that bring their own auth widgets
- support that use case
add `thirdPartyAuth` and friends to the `<LoginPane />` component

feat(LoginPane): enable unstable thirdPartyAuth prop

---

src/semantic-ui-theme/themes/tripwire/globals/site.overrides

Lato is a font that the user will need to download before being displayed. This could result in a poor user experience, especially w/ lag.
We can use 'display: fallback' to display fonts near-immediately w/ a fallback. Lato will be swapped once it's downloaded. 
closes #212

Added 'display: fallback' to Lato fonts

---

src/components/PaginationControl/PaginationControl.jsx
src/styles/components/pagination-control.css

Pagination control has multiple accessibility violations, as reported by various Chrome plugins.
Add title attribute to buttons
Make "Page" text label the page input
Inexplicable change to vertical-align was needed to pass the webjerk snapshots

feat(a11y): Accessibility for pagination control

---

src/components/ThinCard/ThinCardDrawer.jsx

fix(ThinCard): Stop passing "expanded" prop to inner div

---

src/components/charts/AreaChart/AreaChart.jsx
src/components/charts/BarChart/BarChart.jsx
src/components/charts/CircleChart/CircleChart.jsx
src/components/suir/Icon.examples.md

- some handled props are being passed thru as unhandled, and emitting warnings
- `key` is missing on an array
patch

fix(pkgs): handle unhandled props and keys

---

src/components/unstable/LoginPane/LoginPane.examples.md

Full LoginPage has autoFocus set, which overrides the default HTML anchoring. We want components to be accessible via url/#component. 
set autoFocus: false
Added a comment to component to explain why default behavior is unset.
// you will likely want to set autoFocus to true
// set to false to avoid collision with other examples

fix(LoginPane): Fix LoginPane example for component anchoring

---

package.json

Webpack 4 will drop any unused imports unless they are declared to have side effects. We have to declare css files as having side effects (despite the fact that it should be obvious), or webpack will just drop it.
Declare `*.css` as having side effects in package.json
- https://github.com/facebook/create-react-app/issues/5140
Fixes #297

fix(webpack): Fix importing CSS with latest webpack

---

src/components/BannerMessage/BannerMessage.jsx
src/components/unstable/Layout/Layout.css
src/components/unstable/Layout/Layout.jsx
src/styles/components/banner-message.css

The CSS grid Layout provided by Octagon doesn't support having a notification bar between the page content and the Header at the top of the page.
Add a layout variant which has a Notification section.
This also involved a couple tweaks to enable proper styling, by:
* Handling the `className` prop in the BannerMessage component so we can apply our own CSS classes to it
* Removing the `z-index` from the BannerMessage, because it makes the component cover up a drop down menu that comes down from the header above it in the DOM.

feat(layout) add layout for notifications

---

src/components/BannerMessage/BannerMessage.jsx
src/components/unstable/Layout/Layout.css
src/components/unstable/Layout/Layout.jsx
src/styles/components/banner-message.css

The CSS grid Layout provided by Octagon doesn't support having a notification bar between the page content and the Header at the top of the page.
Add a layout variant which has a Notification section.
This is a dup of #309, except targeting the master branch this time.

feat(layout) add layout for notifications (re-do)

---

package.json

Since tests depend on having the styleguide rebuild, automatically
rebuild with a "pretest" command.
Closes #266

chore(testing): Automatically build styleguide before testing

---

src/components/Notification/NotificationEmpty.jsx

update to empty notification to fix typo where 'name' was used instead of 'className'
SUIR violation
noted in #333 "uses class bell_icon, which violates SUIR's propTypes-like-thing"
fix typo 'name' should be 'className'
fixes #333

fix(notification): update to empty notification to fix typo
