Tripwire/octagon

semantic/src/theme.config, semantic/src/themes/tripwire/elements/icon.overrides, semantic/src/themes/tripwire/elements/icon.variables, stories/icons.stories.js
Support for the Elegant Icons component.  The list of available icons is here:
https://www.elegantthemes.com/blog/resources/elegant-icon-font
Since SUI includes the font awesome icon set this extends the supported icons to include elegant fonts icons.  The icons are namespaced as "ei".  Usage retains the SUI syntax.  Example:
`<Icon className='ei' name='icon_folder-alt' size='large' />`
=> feat(icons): support for elegant icons

semantic/src/theme.config, semantic/src/themes/tripwire/collections/table.overrides, semantic/src/themes/tripwire/collections/table.variables, stories/tables.stories.js
Adds support for SUI data tables with TW styling.  Be sure to gulp the semantic components to see new styles.  Full SUI Table docs available [here](http://react.semantic-ui.com/collections/table)
=> Datatables

stories/icons.stories.js
=> Update icon examples

package.json, src/components/charts/AreaChart/Axis.jsx, src/components/charts/BarChart/BarChartTooltip.jsx, src/components/charts/Chart/Axis.jsx, src/components/charts/Chart/ToolTip.jsx, src/components/charts/Chart/TooltipContent.jsx
- see #9
- normal standard is jsx friendly. use blacklisting vs whitelisting
now that its fixed, it caught a few non conforming files, hence the additional changed files
=> fix(pkg): lint. closes #9

src/components/charts/BarChart/BarChart.jsx, src/components/charts/BarChart/BarChartTooltip.jsx, src/components/charts/BarChart/Rect.jsx
Issues identified in #78 #77 and #80 are a WIP on this PR.
=> fix(chart): resolve #77 #78 #80

semantic/src/themes/tripwire/elements/button.overrides, src/styles/components/large-card.css
Update color and button behavior to match that in the TW style guide.
This changes the default as well as the focus, hover and active styles.
=> feat(buttons): update button colors to match style guide

scripts/ci-post-test.js
ci is quiet on sem-rel
make it noisy
=> fix(ci): add publish verbosity

CONTRIBUTING.md
I need a new commit which matches the PR template to trigger a new build. 
I took the opportunity to fix a couple typos in the CONTRIBUTING.md. :)
Woohoo!
=> fix(text): Fix typos

src/components/suir/dimmer/Dimmer.js, src/components/suir/loader/Loader.examples.md, src/components/suir/loader/Loader.js, yarn.lock
- i need some library components!
- bring 'em in!
=> feat(SUIR): expose additional SUIR components

semantic/src/themes/tripwire/elements/button.overrides, semantic/src/themes/tripwire/elements/button.variables, src/components/suir/button/Button.examples.md, yarn.lock
BREAKING CHANGE: Primary & default button colors and spacing all modified.  Please adjust
accordingly.
- Connect team wants some style tweaks to the theme.
- tweak buttons!
- please review the Buttons section when the styleguide publishes
=> feat(Button): hack button spacing & colors to be Connect friendly

src/components/native/LargeCard/LargeCardTitle.jsx, src/styles/components/area-chart.css, src/styles/components/large-card.css, src/styles/components/left-nav.css, src/styles/components/micro-card.css, src/styles/components/notification-item.css, src/styles/components/pagination-control.css, src/styles/components/stop-start-button.css, src/styles/components/tag-button.css, src/styles/components/thin-card.css, src/styles/variables.css
The current Octagon palette doesn't follow Yung or Antoine's themes on UX Pin. Octagon and TOC have begun to diverge. 
Assign variables to colors and to components and types to enable more readability and reuse. Update colors where needed.
This is step one in a long process of bringing consistency across products.
Closes #121
=> refactor(Palette) Updates to palette since doesn't follow a theme correctly

.adr-dir, doc/architecture/decisions/0001-record-architecture-decisions.md, doc/architecture/decisions/0002-components-shall-be-stateless-by-default.md
component statefulness guidelines unclear to active devs
add an adr for the topic
=> docs(adr): stateless components

README.md
=> docs(README): circle badge

doc/architecture/decisions/0003-we-test-via-visual-screenshots.md
- we should define our high level testing strategy
adr for screenshot testing
=> docs(adr): testing via screenshots

scripts/ci-post-test.js
releases are being built, but not published to npm
fix env var
=> fix(ci): correct branch env var

package-lock.json, package.json
#156 build failed because ci was still making env assertions for codeship
migrate to circleci verify conditions
=> fix(ci): remove codeship verify condition, swap in circleci

src/components/native/PaginationControl/PaginationControl.jsx
UI test automation has a hard time selecting the pagination control buttons in the DOM.
Add data-hook attributes to the DOM elements to make them easier to find.
They are not globally unique, but another unique data-hook can be added to the parent component in order to enable tests to find the specific buttons they need to test.
=> feat(pagination): Add data-hooks

src/components/suir/button/Button.js, src/components/suir/card/Card.js, src/components/suir/checkbox/Checkbox.js, src/components/suir/container/Container.js, src/components/suir/dimmer/Dimmer.js, src/components/suir/divider/Divider.js, src/components/suir/dropdown/Dropdown.js, src/components/suir/form/Form.js, src/components/suir/grid/Grid.js, src/components/suir/header/Header.js, src/components/suir/icon/Icon.js, src/components/suir/image/Image.js, src/components/suir/input/Input.js, src/components/suir/item/Item.js, src/components/suir/label/Label.js, src/components/suir/list/List.js, src/components/suir/loader/Loader.js, src/components/suir/menu/Menu.js, src/components/suir/message/Message.js, src/components/suir/modal/Modal.js, src/components/suir/popup/Popup.js, src/components/suir/popup/PopupDemo.js, src/components/suir/progress/Progress.js, src/components/suir/radio/Radio.js, src/components/suir/reveal/Reveal.js, src/components/suir/segment/Segment.js, src/components/suir/sidebar/Sidebar.js, src/components/suir/step/Step.js, src/components/suir/table/Table.js
- our lib creates large bundles
- import from es modules to benefit from tree shaking, vs commonjs dist builds [ref needed]()
=> feat(pkg): commonjs => es suir imports

src/components/suir/button/Button.js, src/components/suir/card/Card.js, src/components/suir/checkbox/Checkbox.js, src/components/suir/container/Container.js, src/components/suir/dimmer/Dimmer.js, src/components/suir/divider/Divider.js, src/components/suir/dropdown/Dropdown.js, src/components/suir/form/Form.js, src/components/suir/grid/Grid.js, src/components/suir/header/Header.js, src/components/suir/icon/Icon.js, src/components/suir/image/Image.js, src/components/suir/input/Input.js, src/components/suir/item/Item.js, src/components/suir/label/Label.js, src/components/suir/list/List.js, src/components/suir/loader/Loader.js, src/components/suir/menu/Menu.js, src/components/suir/message/Message.js, src/components/suir/modal/Modal.js, src/components/suir/popup/Popup.js, src/components/suir/popup/PopupDemo.js, src/components/suir/progress/Progress.js, src/components/suir/radio/Radio.js, src/components/suir/reveal/Reveal.js, src/components/suir/segment/Segment.js, src/components/suir/sidebar/Sidebar.js, src/components/suir/step/Step.js, src/components/suir/table/Table.js
Reverts Tripwire/octagon#174
There were some issues with this merge and tests.
=> Revert "feat(pkg): commonjs => es suir imports"

package.json, src/components/native/TopNav/TopNav.examples.md, src/components/native/TopNav/TopNav.jsx, src/components/native/TopNav/TopNavContent.jsx
- common handled props are not being propagated to root nodes
- proxy handled props to root node
same story, different day.  the issue that keeps on giving ;)
=> fix(TopNav): accept handled props on root nodes

CONTRIBUTING.md
- some reorganization of headers
- added info for styleguidist documentation requirements under "Build Components" section
styleguidist conventions are required for:
component src
component tests/examples
update README, and Contributing as appropriate w/ x-refs
Closes #43
=> docs(README): updates to Contributing.md for documentation styleguidist requirement 

src/components/BannerMessage/BannerMessage.jsx, src/components/BannerMessage/BannerMessageBody.jsx, src/components/BannerMessage/BannerMessageFooter.jsx, src/components/BannerMessage/BannerMessageHeader.jsx, src/components/PaginationControl/PaginationControl.jsx
Some source files have not been correctly formatted with prettier-standard.
Run `yarn format`
This should be happening on every commit, but people have been skipping the pre-commit hook.
The most likely reason for skipping the pre-commit hook is that it runs snapshot tests, which take a long time and will fail if you haven't run a styleguide build and are generally a pain. I think we should get rid of the snaphot test part of the pre-commit hook to encourage people to stop skipping it (which skips the really useful parts of it: linting and formatting).
=> Format source with prettier-standard

CONTRIBUTING.md
Docs don't reference yarn lint or yarn format
update docs
=> docs(formatting): updated contrib to mention yarn lint and yarn format

src/components/BannerMessage/BannerMessage.examples.md
I messed up the semantic release commit format and so a new build wasn't triggered after merging #310.
Add an empty commit to history which *does* follow the format, so a build happens.
=> feat(layout): trigger build

package.json, yarn.lock
Update semantic-ui-react to the latest version
Make peer dependency version for SUIR more flexible
Fix broken lockfile, which should resolve some build issues
Closes #339
=> Update semantic-ui-react and Yarn.lock file

commitlint.config.js, package.json, yarn.lock
Use commitlint to validate commit messages.
Use the angular config/style, since that seems to be what is expected.
Closes #223
=> chore(commit): Use commitlint

src/components/Notification/Notification.jsx
=> feat(docs): added some proptypes

src/components/BannerMessage/BannerMessage.jsx, src/components/unstable/Layout/Layout.jsx
some of the code hasn't been cleaned up re:Standard
yarn lint, yarn format, 
long term is the linter... which is being merged. quick fix is to clean up existing code
=> fix(components): prettify code

src/components/Notification/NotificationBody.jsx
unhandled prop per #334 
handle it.
fixes  #334
=> fix(notification): handle unhandled prop
